name: Dependabot auto-merge
on: pull_request_target
permissions:
  pull-requests: write
  contents: write
jobs:
  dependabot:
    runs-on: ubuntu-latest
    # Only auto-approve changes from dependabot
    if: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}
    steps:
      - id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1.3.1
      - name: Enable auto-merge for Dependabot PRs
        if: ${{steps.dependabot-metadata.outputs.package-ecosystem != 'github_actions'}}
        env:
          GITHUB_TOKEN: ${{secrets.ACTION_PAT}}
        run: gh pr merge --auto --merge "${{github.event.pull_request.html_url}}"
