version: 2
updates:
  # You can also define multiple items with the same ecosystem and different
  # directories for sub-projects
  - package-ecosystem: "docker"
    # by default, works on the default branch
    #target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/example-app/resourceserver"
    # default is 5
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/example-app/client"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/integration-test"
    schedule:
      interval: "daily"
